# Generated by Django 5.2.4 on 2025-09-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('stamp', models.FileField(blank=True, null=True, upload_to='stamps/')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='templates_app.certificatetemplate')),
            ],
        ),
    ]
