# Generated by Django 5.2.4 on 2025-09-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='font',
            field=models.CharField(default='Times-Roman', max_length=100),
        ),
    ]
