# Generated by Django 5.2.4 on 2025-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.CharField(max_length=255),
        ),
    ]
