# Generated by Django 5.2.4 on 2025-09-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mtd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('logos', models.FileField(upload_to='logos/')),
                ('stamps', models.FileField(upload_to='stamps/')),
                ('signature', models.FileField(upload_to='signature/')),
            ],
        ),
    ]
