# Generated by Django 5.2.4 on 2025-09-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mtd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.FileField(upload_to='logos/')),
                ('stamp', models.FileField(upload_to='stamps/')),
                ('signature', models.FileField(upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('assets', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.certificateassets')),
            ],
        ),
        migrations.DeleteModel(
            name='Mtd',
        ),
        migrations.AlterField(
            model_name='student',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.certificatetemplate'),
        ),
    ]
