# Generated by Django 5.2.4 on 2025-09-25 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_certificateassets_certificatetemplate_delete_mtd_and_more'),
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='assets',
        ),
        migrations.AlterField(
            model_name='student',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_app.certificatetemplate'),
        ),
        migrations.DeleteModel(
            name='CertificateAssets',
        ),
        migrations.DeleteModel(
            name='CertificateTemplate',
        ),
    ]
